### PR TITLE
fix creating a replica set client

### PR DESCRIPTION
**Pull request by damoxc**
The host parameter either needs to be a mongodb uri or a list of 'host:port'
strings. Passing in a list of tuples results in a `.split()` does not exist
on `tuple` error being thrown.

I'm just experimenting if it's possible to configure Travis to create a replicaset without too much difficulty and will add a test checking this functionality.

### CODE REVIEW

**Comment by avelino** [comment]
Very very good man!

**Comment by avelino** [comment]
@damoxc This may solve the problem:
https://github.com/travis-ci/travis-ci/issues/1967

    before_script:
        ...
        - sleep 15 
        ...

**Comment by damoxc** [comment]
@avelino Thanks, I think I've found the issue though, it seems to be with oplog creation, it was attempting to allocate 4GB for it, which seems may or may not fail. I tried various methods of delaying `rs.initiate()` including `sleep 60` prior to it

**Comment by avelino** [comment]
When complete, tells me to do merge!

**Comment by damoxc** [comment]
Once this current build passes I'm happy for this to be merged in :smile:

**Pull request merged**
